### ISSUE TITLE
给你一个讨好你们辅导员的机会

### ISSUE THREAD

**Issue by ourongxing** [Cansiny0320/qq-group-bot#2]
使用 We 重邮的 API，扫一遍所有人的学号，就能获取到没打卡的名单，最好把没打卡的存到数据库里，每小时扫一遍。然后可以把学号和 QQ 号匹配上，群里应该都是实名的，就可以自动每小时 @ 没打卡的人了，效果出奇的好。

**Comment by Cansiny0320** [comment]
谢啦 但是这个机器人需要占一个QQ号 我用小号放到私人群（因为有些隐私功能）用的  不太想放到班群

**Comment by ourongxing** [comment]
我的方案是腾讯云函数定时执行脚本，维格表存储数据，Qmsg 酱来推送消息，一分钱不花

**Comment by ourongxing** [comment]
> 谢啦 但是这个机器人需要占一个QQ号 我用小号放到私人群（因为有些隐私功能）用的 不太想放到班群

我的方案是腾讯云函数定时执行脚本，维格表存储数据，Qmsg 酱来推送消息，一分钱不花
