### ISSUE TITLE
windows下进程启动成功但查询不到该进程

### ISSUE THREAD

**Issue by 468336329Zc** [Cansiny0320/qq-group-bot#3]
这样算运行成功么？？？？
但10184进程查询不到。
![image](https://user-images.githubusercontent.com/49133904/136166016-b63645de-1e3b-4b70-897d-aa9783553a39.png)

**Comment by Cansiny0320** [comment]
> 有时候运行之后 页面一直闪 怎么解决
页面一直闪具体是什么意思呢

**Comment by Cansiny0320** [comment]
你可以用 

```shell
yarn dev
```
开发环境看一下 log 信息是什么

**Comment by 468336329Zc** [comment]
> > 应该是没运行成功，测了下qq群 没反应。。
> 
> 你是怎么测试的呢？配置文件写了吗

配置文件写了.env文件
![image](https://user-images.githubusercontent.com/49133904/136313215-04e3b234-77c4-4ca6-bf24-a622e567ced9.png)

在qq群里发送了关键词 教务在线  之类的，机器人没有反应。

**Comment by Cansiny0320** [comment]
> 教务在线

教务在线不是关键词啊 你发个 ”机器人“ 试试

**Comment by Cansiny0320** [comment]
> > 你可以用
> > ```shell
> > yarn dev
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 开发环境看一下 log 信息是什么
> 
> 日志都是正确的，没有什么错误。 ![image](https://user-images.githubusercontent.com/49133904/136313938-a0109f4d-4177-4bc0-974e-108dcd2b03a9.png)

不是这个日志 是机器人的日志 如果你用的 `yarn start` 启动的话 可以用`yarn run log` 看机器人日志或者 `yarn dev`启动可以直接看日志

**Comment by 468336329Zc** [comment]
> > > 你可以用
> > > ```shell
> > > yarn dev
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 开发环境看一下 log 信息是什么
> > 
> > 
> > 日志都是正确的，没有什么错误。 ![image](https://user-images.githubusercontent.com/49133904/136313938-a0109f4d-4177-4bc0-974e-108dcd2b03a9.png)
> 
> 不是这个日志 是机器人的日志 如果你用的 `yarn start` 启动的话 可以用`yarn run log` 看机器人日志或者 `yarn dev`启动可以直接看日志

你是什么多少版本的node

**Comment by Cansiny0320** [comment]
> > > > 你可以用
> > > > ```shell
> > > > yarn dev
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 开发环境看一下 log 信息是什么
> > > 
> > > 
> > > 日志都是正确的，没有什么错误。 ![image](https://user-images.githubusercontent.com/49133904/136313938-a0109f4d-4177-4bc0-974e-108dcd2b03a9.png)
> > 
> > 
> > 不是这个日志 是机器人的日志 如果你用的 `yarn start` 启动的话 可以用`yarn run log` 看机器人日志或者 `yarn dev`启动可以直接看日志
> 
> 你是什么多少版本的node

![image](https://user-images.githubusercontent.com/51797219/136351017-dd88228e-f6bd-4c9d-9682-0e3aee676667.png)
